#cloud-config
timezone: Asia/Tokyo
locale: ja_JP.utf8
package_update: true
package_upgrade: true
packages:
  - unzip
runcmd:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-_ARCH_.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
