#cloud-config
timezone: Asia/Tokyo
locale: ja_JP.utf8
packages:
  - unzip
  - fio
  - jq
  - python3
  - python3-pip
  - zsh
runcmd:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-_ARCH_.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install
  - pip install boto3
  - echo "no_proxy=192.254.192.254" >> /home/_USER_NAME_/.bashrc
  - echo "no_proxy=192.254.192.254" >> /home/_USER_NAME_/.zshrc
