#cloud-config
timezone: Asia/Tokyo
locale: ja_JP.utf8
package_update: true
package_upgrade: true
packages:
  - nftables
runcmd:
  - echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/80-ipv4-forwarding.conf
  - sysctl -w net.ipv4.ip_forward=1
  - systemctl enable --now nftables.service
  - hostnamectl set-hostname NAT-instance
  - /usr/local/bin/ddns.sh
write_files:
  - path: /etc/nftables.conf
    content: |
      #!/usr/sbin/nft -f
      flush ruleset
      table inet filter {
        chain input {
          type filter hook input priority 0;
        }
        chain forward {
          type filter hook forward priority 0;
        }
        chain output {
          type filter hook output priority 0;
        }
      }
      table inet nat {
        chain prerouting {
          type nat hook prerouting priority 0;
        }
        chain postrouting {
          type nat hook postrouting priority 0;
          oifname "ens5" masquerade
        }
      }
    permissions: '0755'
  - path: /usr/local/bin/ddns.sh
    content: |
      #!/bin/bash
      LASTIPFILE=$(realpath ~/.lastipaddr)
      HOST="aws.araike.net"
      APITOKEN="DeWi3Ve8HzWTXG81NzonjHTsAj98F--1rMUVBERw"
      ZONEID="1238400fe3a082a0a78ec9e233e03da7"
      RECORDID="622e062b7d0714803c5294d9de6d0ad2"
      IP=$(curl -s https://checkip.amazonaws.com)
      if [ -z "$IP" ]; then
        echo "Failed to check global IP address. Network could be down. There's nothing we can do now."
        exit 1
      fi
      if ! touch $LASTIPFILE; then
        echo "We don't have access on \"$LASTIPFILE\". Please check permission settings."
        exit 2
      fi
      LASTIP=$(<$LASTIPFILE)
      if [ $IP != "$LASTIP" ]; then
        echo "Updating DNS record."
        echo $IP
        curl -X PATCH "https://api.cloudflare.com/client/v4/zones/$ZONEID/dns_records/$RECORDID" \
          -H "Authorization: Bearer $APITOKEN" \
          -H "Content-Type: application/json" \
          --data "{\"type\":\"A\",\"name\":\"$HOST\",\"content\":\"$IP\",\"ttl\":1,\"proxied\":false}"
        echo $IP > $LASTIPFILE
      fi
    permissions: '0755'
